from constants import (DATA_DIR, REPORTS_DIR, PRODUCTS_FILE, NUTRITION_FILE, PRODUCT_COUNTRIES_FILE, COUNTRY_REGIONS_FILE, COUNTRY_TRENDS_FILE, REGION_TRENDS_FILE, DATA_SOURCES_FILE, EXIT_OPTION )

def create_required_folders